remote_theme: daattali/beautiful-jekyll
title: Stephanie Noble's Research
author: Stephanie Noble
description: All things academia.

# --- List of links in the navigation bar --- #

navbar-links:
  About Me: "aboutme"
  Publications: "https://scholar.google.com/citations?user=JxQdvn4AAAAJ&hl=en&oi=sra"

# --- Logo --- #

avatar: "/assets/img/profile_photo_2018_square.jpeg"

# --- Footer options --- #

# Select the social network links that you want to show in the footer.
# Uncomment the links you want to show and add your information to each one.
# If you don't want to show a link to an RSS feed, set rss to "false".
social-network-links:
  email: "stephanie.noble@yale.edu"
  github: sNeuroble
  twitter: sNeuroble
  linkedin: sNeuroble
  
# --- Colours / background image --- #

# mobile-theme-col: "#0085A1"
